import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { getDatabase, ref, onValue } from "firebase/database";
import { initializeApp } from "firebase/app";
import { firebaseConfig } from '../constants/firebase-config';
import { ReviewRow } from '../components/ReviewRow';
import { TitleBar } from '../components/TitleBar';

const inter = Inter({ subsets: ['latin'] })
export default function Home({ reviews }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TitleBar />
        <p>{reviews.review}</p>
        {
          reviews.map((review: any) =>
            <ReviewRow review={review} />
          )
        }
      </main>
    </>
  )
}

export async function getStaticProps() {
  const app = initializeApp(firebaseConfig);
  const database = getDatabase(app);
  const dbRef = ref(database, '/reviews');
  const reviews: any[] = []

  onValue(dbRef, (snapshot) => {
    snapshot.forEach((childSnapshot) => {
      const childData = childSnapshot.val();
      reviews.push(childData)
    });
  }, {
    onlyOnce: false
  });
  console.log(reviews)
  return {
    props: {
      reviews,
    },
  }
}